---
name: Bug Report
description: Report a bug or issue with MorphLib
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and reproduce the issue.

        **Important**: MorphLib is a library mod that provides data management only. It does not implement visual changes or player model modifications. If you're experiencing issues with visual appearance, please report to the mod that uses MorphLib for rendering.

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you using?
      placeholder: "1.21.4"
    validations:
      required: true

  - type: dropdown
    id: mod-loader
    attributes:
      label: Mod Loader
      description: Which mod loader are you using?
      options:
        - NeoForge
        - Fabric
    validations:
      required: true

  - type: input
    id: loader-version
    attributes:
      label: Mod Loader Version
      description: What version of the mod loader are you using?
      placeholder: "21.0.133 or 0.15.11"
    validations:
      required: true

  - type: input
    id: morphlib-version
    attributes:
      label: MorphLib Version
      description: What version of MorphLib are you using?
      placeholder: "0.1"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is with MorphLib's data management or API.
      placeholder: "When I call MorphManager.applyMorph(), the data is not synchronized to the client..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Call MorphManager.applyMorph(player, morphData)
        2. Query MorphCache.getInstance().getInterpolatedState(uuid, 0.0f)
        3. Observed behavior: data is null or incorrect
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: "The MorphState should be stored and retrievable with the correct proportions."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: "The MorphState is null or has incorrect values after applying morph data."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please provide relevant log excerpts. Use a paste service for long logs.
      placeholder: |
        [latest.log excerpt]
        [debug.log excerpt if relevant]
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: |
        - Other mods installed
        - Server or singleplayer
        - Any error messages
        - Screenshots if visual issues
    validations:
      required: false
